database:
    debug: false
    driver: mysql
    host: localhost
    name: secure_file_box
    password: "0827"
    port: 3306
    user: root
file_crypto:
    key: -PHiHBq5y8VBwoxlSpMW8EtA8VxRcxS3vH6tymOvdeI
jwt:
    audience: secure_users
    issuer: secure_file_box
    secret: jvSn7d0cJO8iHA_-H8qomIV1--vCt2keBnEP4oVbTwQ
server:
    app_name: secure_file_box
    debug: true
    env: development
    host: 127.0.0.1
    port: 8080
    time_zone: Asia/Shanghai
