database:
    debug: false
    driver: mysql
    host: localhost
    name: secure_file_box
    password: "0827"
    port: 3306
    user: root
file_crypto:
    key: pju2nskrZdZ6X0zXeDt91lcjkEBqdOuLDbnOusNK9dM
jwt:
    audience: secure_users
    issuer: secure_file_box
    secret: LL6FFyTyLLh9My7v9ySCHXxn6LL5z4tBiItAXfwdm6M
server:
    app_name: secure_file_box
    debug: true
    env: development
    host: 127.0.0.1
    port: 8080
    time_zone: Asia/Shanghai
