database:
    debug: false
    driver: mysql
    host: localhost
    name: secure_file_box
    password: "0827"
    port: 3306
    user: root
file_crypto:
    key: ncevW3LVoKZU2ZfHmDe0svmtMv-1NzjupMCwcmMQcUA
jwt:
    audience: secure_users
    issuer: secure_file_box
    secret: vyYSgzQqZUQIn6Fi968jGy_pf1qzqO1sj898o47G3sg
server:
    app_name: secure_file_box
    debug: true
    env: development
    host: 127.0.0.1
    port: 8080
    time_zone: Asia/Shanghai
