database:
    debug: false
    driver: mysql
    host: localhost
    name: secure_file_box
    password: "0827"
    port: 3306
    user: root
file_crypto:
    key: OGhnVSz_Nhs14EUBnK9h3rvv-96AwMQJaAnOOpQy5h0
jwt:
    audience: secure_users
    issuer: secure_file_box
    secret: YqOzIxgod1-zuCXGxQ6N6xQBksSX-7ac5Xpswfy5qk0
server:
    app_name: secure_file_box
    debug: true
    env: development
    host: 127.0.0.1
    port: 8080
    time_zone: Asia/Shanghai
